apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: cflynnus/blog
      sync:
        manual:
          - src: '**/*.html'
            dest: '/go/src/myblog'
          - src: '**/*.md'
            dest: '/go/src/myblog'
          - src: '**/*.css'
            dest: '/go/src/myblog'
          - src: '**/*.png'
            dest: '/go/src/myblog'
          - src: '**/*.scss'
            dest: '/go/src/myblog'
          - src: '**/*.js'
            dest: '/go/src/myblog'
      context: .
      docker:
        dockerfile: Dockerfile-develop
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - "kubernetes/local.yaml"
