apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
    - image: cflynnus/blog
      context: .
      docker:
        dockerfile: Dockerfile-develop
      sync:
        '**/*.html': "/go/src/myblog"
        '**/*.md': "/go/src/myblog"
        '**/*.css': "/go/src/myblog"
        '**/*.png': "/go/src/myblog"
deploy:
  kubectl:
    manifests:
      - "kubernetes/local.yaml"
