apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: cflynnus/myblog
    context: .
    sync:
      '**/*.html': "/root"
      '**/*.md': "/root"
      '**/*.css': "/root"
      '**/*.png': "/root"
deploy:
  helm:
    releases:
      - name: "myblog"
        chartPath: "helm"
