apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: cflynnus/myblog
    context: .
    sync:
      '**/*.html': .
      '**/*.md': .
      '**/*.css': .
      '**/*.png': .
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
