apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog.name" . }}-develop-app
  # namespace: {{ include "blog.name" . }}
  labels:
    app: {{ include "blog.name" . }}-develop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "blog.name" . }}-develop-app
  template:
    metadata:
      labels:
        app: {{ include "blog.name" . }}-develop-app
    spec:
      containers:
        - name: {{ include "blog.name" . }}
          image: {{ $.Values.develop_image }}
          env:
            - name: PORT
              value: "80"
            - name: SSL_REDIRECT
              value: "false"
            - name: DEPLOYMENT_TIME
              value: {{ $.Values.deployment_time }}
            - name: DEPLOYMENT_SHA
              value: {{ $.Values.deployment_sha }}
            - name: ACTION_ID
              value: {{ $.Values.action_id }}
          ports:
            - name: {{ include "blog.name" . }}-port
              containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
