apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blog.name" . }}-master-app
  # namespace: {{ include "blog.name" . }}
  labels:
    app: {{ include "blog.name" . }}-master-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "blog.name" . }}-master-app
  template:
    metadata:
      labels:
        app: {{ include "blog.name" . }}-master-app
    spec:
      containers:
        - name: {{ include "blog.name" . }}
          image: {{ $.Values.master_image }}
          env:
            - name: PORT
              value: "80"
            - name: SSL_REDIRECT
              value: "true"
            {{- if ne $.Values.google_analytics "" }}
            - name: GOOGLE_ANALYTICS
              value: {{ $.Values.google_analytics | quote }}
            {{- end }}
            - name: DEPLOYMENT_TIME
              value: {{ $.Values.master_deployment_time }}
            - name: DEPLOYMENT_SHA
              value: {{ $.Values.master_deployment_sha }}
          ports:
            - name: {{ include "blog.name" . }}-port
              containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
