apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  # namespace: {{ include "blog.fullname" . }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-static-ip
    networking.gke.io/managed-certificates: cflynnus-certificate
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cflynn.us
    http:
      paths:
      - path: /*
        backend:
          serviceName: blog-master-app
          servicePort: 80
  - host: cflynn-blog.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: blog-develop-app
          servicePort: 80
