apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.name" . }}-develop-app
  # namespace: {{ include "blog.name" . }}
  labels:
    app: {{ include "blog.name" . }}-develop-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ include "blog.name" . }}-port
      protocol: TCP
      name: http
  selector:
    app: {{ include "blog.name" . }}-develop-app
