version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/app
    steps:
      - checkout #checks out the source code to working directory
      - run:
          name: Run E2E tests
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Just testing
          command: ls -la
      - run:
          name: Upload coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
