version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/app
    steps:
      - checkout #checks out the source code to working directory
      - run:
          name: Run E2E tests
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Upload coverage report to codecov
          command: bash <(curl -s https://codecov.io/bash)
  deploy_to_staging:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/app
    steps:
      - checkout
      - run:
          name: testing CI run step
          command: ls -l
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy_to_staging:
          requires:
            - build_and_test
          filters:
            branches:
              only: develop
