apiVersion: v1
kind: Namespace
metadata:
  name: ${PROJECT_NAME}

---

apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
type: Opaque
# Create an empty secret (with no data) in order for the update to work

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: ${PROJECT_NAME}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cflynn.us
    http:
      paths:
      - path: /*
        backend:
          serviceName: blog-master-app
          servicePort: 80
  - host: cflynn-blog.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: blog-develop-app
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app
  namespace: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: ${PROJECT_NAME}-port
      protocol: TCP
      name: http
  selector:
    app: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app
  namespace: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}-${CIRCLE_BRANCH}-app
    spec:
      initContainers:
        - name: ${PROJECT_NAME}-init
          image: busybox
          command: ['sh', '-c', 'echo this is a test']
      containers:
        - name: ${PROJECT_NAME}
          image: cflynnus/${PROJECT_NAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
          env:
            - name: PORT
              value: "80"
          ports:
            - name: ${PROJECT_NAME}-port
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80

---

apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      # Bash script that starts an http server and launches certbot
      # Fork of github.com/sjenning/kube-nginx-letsencrypt
        - image: quay.io/hiphipjorge/kube-nginx-letsencrypt:latest
          name: letsencrypt
          imagePullPolicy: Always
          ports:
          - name: letsencrypt
            containerPort: 80
          env:
          - name: DOMAINS
            value: cflynn.us
          - name: EMAIL
            value: cflynn.us@gmail.com
          - name: SECRET
            value: letsencrypt-certs
        restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: letsencrypt
spec:
  selector:
    app: letsencrypt
  ports:
  - protocol: "TCP"
    port: 80
