apiVersion: v1
kind: Namespace
metadata:
  name: blog

---

apiVersion: v1
kind: Service
metadata:
  name: blog-app
  namespace: blog
  labels:
    app: blog-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: blog-port
      protocol: TCP
      name: http
  selector:
    app: blog-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: blog
  labels:
    app: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      initContainers:
        - name: blog-init
          image: busybox
          command: ['sh', '-c', 'echo this is a test']
      containers:
        - name: blog
          image: cflynnus/myblog:latest
          env:
            - name: PORT
              value: "80"
          ports:
            - name: blog-port
              containerPort: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
