apiVersion: v1
kind: Namespace
metadata:
  name: blog

---

apiVersion: v1
kind: Service
metadata:
  name: blog-app
  namespace: blog
  labels:
    app: blog-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: blog-port
      protocol: TCP
      name: http
  selector:
    app: blog-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: blog
  labels:
    app: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog
          image: cflynnus/blog:latest
          env:
            - name: PORT
              value: 80
            - name: DEPLOYMENT_TIME
              value: 2020-01-14 15:10pm
            - name: DEPLOYMENT_SHA
              value: 5efd24ebfb06f5423803358162db78c7b5530bc3
          ports:
            - name: blog-port
              containerPort: 80
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
