name: Test, Build and Deploy
on:
  push:
    branches:
      - master
      - circleci-to-github-actions
jobs:
  test:
    name: test
    runs-on: docker://golang:1.12.9
    steps:
      - run: go test ./...
