name: Test, Build and Deploy
on: [push]

# env:
#   GKE_PROJECT:
#   GKE_EMAIL:
#   GKE_ZONE:
#   GKE_CLUSTER: 

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Go Test
        uses: cedrickring/golang-action/go1.12@1.3.0
        with:
          args: go test ./... -coverprofile=coverage.txt -covermode=atomic -coverpkg=myblog/app
        env:
          GO111MODULE: on
          GOFLAGS: -mod=vendor
      - name: Upload Coverage
        run: curl -s https://codecov.io/bash | bash -s -- -t ${{secrets.CODECOV_TOKEN}} -f ./coverage.txt
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Docker Login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Docker Build
        # | ::set-env explanation
        # Bit of non-dry code here, also copied to the "Deploy to Staging" job to calculate ENVs
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env
        run: |
          echo "GITHUB_REF: $GITHUB_REF"; \
          BRANCH_NAME="`echo $GITHUB_REF | awk -F'/' '{print $3}'`"; \
          echo "BRANCH_NAME: $BRANCH_NAME"; \
          IMAGE_TAG_NAME="cflynnus/blog:${BRANCH_NAME}-${GITHUB_SHA}"; \
          echo "IMAGE_TAG_NAME: $IMAGE_TAG_NAME"; \
          echo "::set-env name=IMAGE_TAG_NAME::$IMAGE_TAG_NAME"; \
          docker build . --file Dockerfile -t $IMAGE_TAG_NAME;
      - name: Docker Tag Latest
        run: docker tag "$IMAGE_TAG_NAME" cflynnus/blog:latest
      - name: Docker Push Tags
        run: |
          echo "IMAGE_TAG_NAME: $IMAGE_TAG_NAME"; \
          docker push "$IMAGE_TAG_NAME"; \
          docker push cflynnus/blog:latest;
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Envs
        # | ::set-env explanation
        # Bit of non-dry code here, also copied to the "Deploy to Staging" job to calculate ENVs
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env
        run: |
          echo "GITHUB_REF: $GITHUB_REF"; \
          BRANCH_NAME="`echo $GITHUB_REF | awk -F'/' '{print $3}'`"; \
          echo "BRANCH_NAME: $BRANCH_NAME"; \
          IMAGE_TAG_NAME="cflynnus/blog:${BRANCH_NAME}-${GITHUB_SHA}"; \
          echo "IMAGE_TAG_NAME: $IMAGE_TAG_NAME"; \
          echo "::set-env name=IMAGE_TAG_NAME::$IMAGE_TAG_NAME"; \
      - name: Google Cloud Authenticate
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{secrets.GCLOUD_AUTH}}
      - name: GC Set Project ID
        uses: actions/gcloud/cli@master
        env:
          GCLOUD_PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        with:
          args: config set project ${GCLOUD_PROJECT_ID}
      - name: GC set compute/zone
        uses: actions/gcloud/cli@master
        env:
          GCLOUD_COMPUTE_ZONE: ${{secrets.GCLOUD_COMPUTE_ZONE}}
        with:
          args: config set compute/zone ${GCLOUD_COMPUTE_ZONE}
      - name: GC get-credentials
        uses: actions/gcloud/cli@master
        env:
          GCLOUD_CLUSTER_NAME: ${{secrets.GCLOUD_CLUSTER_NAME}}
        with:
          args: container clusters get-credentials ${GCLOUD_CLUSTER_NAME}
      - name: GCP List Containers
        uses: actions/gcloud/cli@master
        with:
          args: container clusters list
      - name: Helm Deploy Develop
        if: github.ref == 'refs/heads/develop'
        uses: cflynn07/gha-helm3@master
        with:
          args: status blog
        # with: 
        #  args: list
        #          args: |
        #            upgrade blog \
        #              --install \
        #              --reuse-values \
        #              --debug \
        #              --set develop_image="$IMAGE_TAG_NAME" \
        #              ./helm
      - name: Helm Deploy Master
        uses: cflynn07/gha-helm3@master
        if: github.ref == 'refs/heads/master'
        with: 
          args: |
            upgrade blog \
              --install \
              --reuse-values \
              --debug \
              --set master_image="$IMAGE_TAG_NAME" \
              ./helm
