name: Test, Build and Deploy
on:
  push:
    branches:
      - master
      - circleci-to-github-actions
jobs:
  test:
    name: test
    runs-on: docker://golang:1.12.9
    steps:
      - uses: actions/checkout@master
      - name: Display the path
        run: echo ${PATH}
        shell: bash
