name: Test, Build and Deploy
on:
  push:
    branches:
      - master
      - circleci-to-github-actions
jobs:
  test:
    name: test
    runs-on: docker://golang:1.12.9
    steps:
      - uses: actions/checkout@master
      - name: Go Test
        uses: cedrickring/golang-action/go1.12@1.3.0
        env:
          GO111MODULE: "on"
